# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Documentos\UNIVERSIDAD\5to 2016-2017\TFG\Interfaz grafica\actividades.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(745, 488)
        Dialog.setMinimumSize(QtCore.QSize(745, 488))
        Dialog.setMaximumSize(QtCore.QSize(745, 488))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("plantillas/WA.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.listWidget_act = QtWidgets.QListWidget(Dialog)
        self.listWidget_act.setGeometry(QtCore.QRect(10, 10, 251, 461))
        self.listWidget_act.setObjectName("listWidget_act")
        self.btn_editAct = QtWidgets.QPushButton(Dialog)
        self.btn_editAct.setEnabled(False)
        self.btn_editAct.setGeometry(QtCore.QRect(280, 20, 93, 28))
        self.btn_editAct.setObjectName("btn_editAct")
        self.btn_deleteAct = QtWidgets.QPushButton(Dialog)
        self.btn_deleteAct.setEnabled(False)
        self.btn_deleteAct.setGeometry(QtCore.QRect(560, 20, 93, 28))
        self.btn_deleteAct.setObjectName("btn_deleteAct")
        self.txt_lugarAct = QtWidgets.QTextEdit(Dialog)
        self.txt_lugarAct.setEnabled(False)
        self.txt_lugarAct.setGeometry(QtCore.QRect(280, 330, 451, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_lugarAct.setFont(font)
        self.txt_lugarAct.setObjectName("txt_lugarAct")
        self.txt_nombAct = QtWidgets.QTextEdit(Dialog)
        self.txt_nombAct.setEnabled(False)
        self.txt_nombAct.setGeometry(QtCore.QRect(280, 80, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_nombAct.setFont(font)
        self.txt_nombAct.setObjectName("txt_nombAct")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(470, 430, 55, 21))
        self.label_12.setObjectName("label_12")
        self.fecha_act = QtWidgets.QDateEdit(Dialog)
        self.fecha_act.setEnabled(False)
        self.fecha_act.setGeometry(QtCore.QRect(330, 430, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fecha_act.setFont(font)
        self.fecha_act.setObjectName("fecha_act")
        self.hora_acr = QtWidgets.QTimeEdit(Dialog)
        self.hora_acr.setEnabled(False)
        self.hora_acr.setGeometry(QtCore.QRect(510, 430, 118, 31))
        self.hora_acr.setObjectName("hora_acr")
        self.txt_descAct = QtWidgets.QPlainTextEdit(Dialog)
        self.txt_descAct.setEnabled(False)
        self.txt_descAct.setGeometry(QtCore.QRect(280, 130, 451, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_descAct.setFont(font)
        self.txt_descAct.setObjectName("txt_descAct")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(288, 430, 61, 21))
        self.label_13.setObjectName("label_13")
        self.btn_cancelEditAct = QtWidgets.QPushButton(Dialog)
        self.btn_cancelEditAct.setEnabled(False)
        self.btn_cancelEditAct.setGeometry(QtCore.QRect(380, 20, 111, 28))
        self.btn_cancelEditAct.setObjectName("btn_cancelEditAct")
        self.btn_guardarAct = QtWidgets.QPushButton(Dialog)
        self.btn_guardarAct.setEnabled(False)
        self.btn_guardarAct.setGeometry(QtCore.QRect(650, 430, 81, 28))
        self.btn_guardarAct.setInputMethodHints(QtCore.Qt.ImhSensitiveData)
        self.btn_guardarAct.setCheckable(False)
        self.btn_guardarAct.setFlat(False)
        self.btn_guardarAct.setObjectName("btn_guardarAct")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Actividades"))
        self.btn_editAct.setText(_translate("Dialog", "Editar"))
        self.btn_deleteAct.setText(_translate("Dialog", "Eliminar"))
        self.txt_lugarAct.setPlaceholderText(_translate("Dialog", "Lugar"))
        self.txt_nombAct.setPlaceholderText(_translate("Dialog", "Nombre"))
        self.label_12.setText(_translate("Dialog", "Hora: "))
        self.txt_descAct.setPlaceholderText(_translate("Dialog", "Descripción"))
        self.label_13.setText(_translate("Dialog", "Fecha: "))
        self.btn_cancelEditAct.setText(_translate("Dialog", "Cancelar edición"))
        self.btn_guardarAct.setText(_translate("Dialog", "Guardar"))

