# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Documentos\UNIVERSIDAD\5to 2016-2017\TFG\Interfaz grafica\nuevoProyecto.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_NuevoProyecto(object):
    def setupUi(self, NuevoProyecto):
        NuevoProyecto.setObjectName("NuevoProyecto")
        NuevoProyecto.resize(965, 629)
        NuevoProyecto.setMinimumSize(QtCore.QSize(965, 629))
        NuevoProyecto.setMaximumSize(QtCore.QSize(965, 629))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("plantillas/WA.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        NuevoProyecto.setWindowIcon(icon)
        self.lbl_nombreProy = QtWidgets.QLabel(NuevoProyecto)
        self.lbl_nombreProy.setGeometry(QtCore.QRect(20, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_nombreProy.setFont(font)
        self.lbl_nombreProy.setObjectName("lbl_nombreProy")
        self.txt_nombProy = QtWidgets.QTextEdit(NuevoProyecto)
        self.txt_nombProy.setEnabled(True)
        self.txt_nombProy.setGeometry(QtCore.QRect(190, 20, 631, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_nombProy.setFont(font)
        self.txt_nombProy.setMouseTracking(False)
        self.txt_nombProy.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_nombProy.setObjectName("txt_nombProy")
        self.lbl_nombWeb = QtWidgets.QLabel(NuevoProyecto)
        self.lbl_nombWeb.setGeometry(QtCore.QRect(20, 80, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_nombWeb.setFont(font)
        self.lbl_nombWeb.setObjectName("lbl_nombWeb")
        self.txt_nomWeb = QtWidgets.QTextEdit(NuevoProyecto)
        self.txt_nomWeb.setGeometry(QtCore.QRect(190, 80, 631, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_nomWeb.setFont(font)
        self.txt_nomWeb.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_nomWeb.setReadOnly(False)
        self.txt_nomWeb.setObjectName("txt_nomWeb")
        self.groupBox = QtWidgets.QGroupBox(NuevoProyecto)
        self.groupBox.setGeometry(QtCore.QRect(10, 130, 481, 211))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.lbl_telef = QtWidgets.QLabel(self.groupBox)
        self.lbl_telef.setGeometry(QtCore.QRect(20, 40, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_telef.setFont(font)
        self.lbl_telef.setObjectName("lbl_telef")
        self.txt_telef = QtWidgets.QTextEdit(self.groupBox)
        self.txt_telef.setEnabled(True)
        self.txt_telef.setGeometry(QtCore.QRect(100, 30, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.txt_telef.setFont(font)
        self.txt_telef.setMouseTracking(False)
        self.txt_telef.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_telef.setObjectName("txt_telef")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 90, 141, 16))
        self.label.setObjectName("label")
        self.txt_email = QtWidgets.QTextEdit(self.groupBox)
        self.txt_email.setGeometry(QtCore.QRect(100, 80, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_email.setFont(font)
        self.txt_email.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_email.setObjectName("txt_email")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 81, 16))
        self.label_2.setObjectName("label_2")
        self.txt_dir = QtWidgets.QTextEdit(self.groupBox)
        self.txt_dir.setGeometry(QtCore.QRect(100, 130, 371, 71))
        self.txt_dir.setObjectName("txt_dir")
        self.groupBox_2 = QtWidgets.QGroupBox(NuevoProyecto)
        self.groupBox_2.setGeometry(QtCore.QRect(510, 130, 441, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.lbl_logo = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_logo.setGeometry(QtCore.QRect(20, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_logo.setFont(font)
        self.lbl_logo.setObjectName("lbl_logo")
        self.selec_logo = QtWidgets.QToolButton(self.groupBox_2)
        self.selec_logo.setGeometry(QtCore.QRect(400, 30, 31, 31))
        self.selec_logo.setObjectName("selec_logo")
        self.txt_logo = QtWidgets.QTextEdit(self.groupBox_2)
        self.txt_logo.setEnabled(False)
        self.txt_logo.setGeometry(QtCore.QRect(100, 30, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_logo.setFont(font)
        self.txt_logo.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_logo.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.txt_logo.setObjectName("txt_logo")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txt_resumen = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.txt_resumen.setGeometry(QtCore.QRect(100, 90, 331, 81))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_resumen.setFont(font)
        self.txt_resumen.setObjectName("txt_resumen")
        self.label_4 = QtWidgets.QLabel(NuevoProyecto)
        self.label_4.setGeometry(QtCore.QRect(30, 380, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txt_sobrenos = QtWidgets.QPlainTextEdit(NuevoProyecto)
        self.txt_sobrenos.setGeometry(QtCore.QRect(20, 410, 281, 161))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_sobrenos.setFont(font)
        self.txt_sobrenos.setObjectName("txt_sobrenos")
        self.label_5 = QtWidgets.QLabel(NuevoProyecto)
        self.label_5.setGeometry(QtCore.QRect(370, 380, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.txt_hist = QtWidgets.QPlainTextEdit(NuevoProyecto)
        self.txt_hist.setGeometry(QtCore.QRect(320, 410, 301, 161))
        self.txt_hist.setObjectName("txt_hist")
        self.label_6 = QtWidgets.QLabel(NuevoProyecto)
        self.label_6.setGeometry(QtCore.QRect(510, 340, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.listWidget_juntadir = QtWidgets.QListWidget(NuevoProyecto)
        self.listWidget_juntadir.setGeometry(QtCore.QRect(650, 420, 291, 151))
        self.listWidget_juntadir.setObjectName("listWidget_juntadir")
        self.txt_juntaDir = QtWidgets.QTextEdit(NuevoProyecto)
        self.txt_juntaDir.setGeometry(QtCore.QRect(630, 330, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txt_juntaDir.setFont(font)
        self.txt_juntaDir.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_juntaDir.setObjectName("txt_juntaDir")
        self.btn_addJuntaDir = QtWidgets.QPushButton(NuevoProyecto)
        self.btn_addJuntaDir.setGeometry(QtCore.QRect(910, 330, 31, 31))
        self.btn_addJuntaDir.setObjectName("btn_addJuntaDir")
        self.btn_elimJuntadir = QtWidgets.QPushButton(NuevoProyecto)
        self.btn_elimJuntadir.setGeometry(QtCore.QRect(870, 390, 71, 28))
        self.btn_elimJuntadir.setObjectName("btn_elimJuntadir")
        self.label_7 = QtWidgets.QLabel(NuevoProyecto)
        self.label_7.setGeometry(QtCore.QRect(650, 390, 241, 20))
        self.label_7.setObjectName("label_7")
        self.btn_guardarProy = QtWidgets.QPushButton(NuevoProyecto)
        self.btn_guardarProy.setGeometry(QtCore.QRect(390, 590, 93, 28))
        self.btn_guardarProy.setObjectName("btn_guardarProy")
        self.btn_cancelar = QtWidgets.QPushButton(NuevoProyecto)
        self.btn_cancelar.setGeometry(QtCore.QRect(510, 590, 93, 28))
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.groupBox_2.raise_()
        self.lbl_nombreProy.raise_()
        self.txt_nombProy.raise_()
        self.lbl_nombWeb.raise_()
        self.txt_nomWeb.raise_()
        self.groupBox.raise_()
        self.label_4.raise_()
        self.txt_sobrenos.raise_()
        self.label_5.raise_()
        self.txt_hist.raise_()
        self.label_6.raise_()
        self.listWidget_juntadir.raise_()
        self.txt_juntaDir.raise_()
        self.btn_addJuntaDir.raise_()
        self.btn_elimJuntadir.raise_()
        self.label_7.raise_()
        self.btn_guardarProy.raise_()
        self.btn_cancelar.raise_()

        self.retranslateUi(NuevoProyecto)
        self.btn_cancelar.clicked.connect(NuevoProyecto.close)
        QtCore.QMetaObject.connectSlotsByName(NuevoProyecto)

    def retranslateUi(self, NuevoProyecto):
        _translate = QtCore.QCoreApplication.translate
        NuevoProyecto.setWindowTitle(_translate("NuevoProyecto", "Proyecto nuevo"))
        self.lbl_nombreProy.setText(_translate("NuevoProyecto", "Nombre del proyecto: "))
        self.txt_nombProy.setHtml(_translate("NuevoProyecto", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.txt_nombProy.setPlaceholderText(_translate("NuevoProyecto", "Ej.: Asociacion_vecinos, proyecto1, ProyectoAsociacion (máx 30 caracteres)"))
        self.lbl_nombWeb.setText(_translate("NuevoProyecto", "Nombre del sitio web:"))
        self.txt_nomWeb.setPlaceholderText(_translate("NuevoProyecto", "Ej.: Asociación de vecinos de Lagunas (máx 40 caracteres)"))
        self.groupBox.setTitle(_translate("NuevoProyecto", "Contacto"))
        self.lbl_telef.setText(_translate("NuevoProyecto", "Teléfono: "))
        self.txt_telef.setHtml(_translate("NuevoProyecto", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.txt_telef.setPlaceholderText(_translate("NuevoProyecto", "Ej.: 999888777"))
        self.label.setText(_translate("NuevoProyecto", "Email:"))
        self.txt_email.setPlaceholderText(_translate("NuevoProyecto", "Ej.: mi_correo@electronico.es"))
        self.label_2.setText(_translate("NuevoProyecto", "Dirección: "))
        self.txt_dir.setPlaceholderText(_translate("NuevoProyecto", "Calle, número, piso puerta, CP, Ciudad"))
        self.groupBox_2.setTitle(_translate("NuevoProyecto", "Opcional"))
        self.lbl_logo.setText(_translate("NuevoProyecto", "Logotipo:"))
        self.selec_logo.setText(_translate("NuevoProyecto", "..."))
        self.txt_logo.setPlaceholderText(_translate("NuevoProyecto", "jpg, png"))
        self.label_3.setText(_translate("NuevoProyecto", "Resumen:"))
        self.txt_resumen.setPlaceholderText(_translate("NuevoProyecto", "Breve resumen sobre el sitio web"))
        self.label_4.setText(_translate("NuevoProyecto", "Información sobre la asociación:"))
        self.txt_sobrenos.setPlaceholderText(_translate("NuevoProyecto", "¿Quiénes somos? ¿Qué hacemos?"))
        self.label_5.setText(_translate("NuevoProyecto", "Historia de la asociación:"))
        self.label_6.setText(_translate("NuevoProyecto", "Junta directiva:"))
        self.txt_juntaDir.setPlaceholderText(_translate("NuevoProyecto", "Introduzca nombre y apellidos"))
        self.btn_addJuntaDir.setText(_translate("NuevoProyecto", "+"))
        self.btn_elimJuntadir.setText(_translate("NuevoProyecto", "Eliminar "))
        self.label_7.setText(_translate("NuevoProyecto", "Seleccione nombre para eliminar"))
        self.btn_guardarProy.setText(_translate("NuevoProyecto", "Guardar"))
        self.btn_cancelar.setText(_translate("NuevoProyecto", "Cancelar"))

