# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Documentos\UNIVERSIDAD\5to 2016-2017\TFG\Interfaz grafica\AsistenteWebescalado.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1011, 679)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1011, 679))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 138, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 138, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(227, 227, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 138, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 234, 234))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 138, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(153, 153, 153))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 138, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(138, 138, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("plantillas/WA.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tab = QtWidgets.QTabWidget(self.centralwidget)
        self.tab.setEnabled(True)
        self.tab.setMinimumSize(QtCore.QSize(1011, 628))
        self.tab.setMaximumSize(QtCore.QSize(1011, 628))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 199, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 200, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 228, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 250, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 199, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 200, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 228, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 250, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 200, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 199, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 200, 214))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(214, 228, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(81, 89, 95))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 117, 125))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 250, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 246, 250))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.tab.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial Unicode MS")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tab.setFont(font)
        self.tab.setMouseTracking(False)
        self.tab.setTabletTracking(False)
        self.tab.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tab.setAcceptDrops(False)
        self.tab.setAutoFillBackground(True)
        self.tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab.setDocumentMode(False)
        self.tab.setTabBarAutoHide(False)
        self.tab.setObjectName("tab")
        self.tabInicio = QtWidgets.QWidget()
        self.tabInicio.setObjectName("tabInicio")
        self.label = QtWidgets.QLabel(self.tabInicio)
        self.label.setGeometry(QtCore.QRect(50, 10, 881, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 199, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 199, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 199, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 247, 247))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 199, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(199, 199, 199))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 199, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(187, 199, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lbl_version = QtWidgets.QLabel(self.tabInicio)
        self.lbl_version.setGeometry(QtCore.QRect(740, 570, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lbl_version.setFont(font)
        self.lbl_version.setObjectName("lbl_version")
        self.lbl_autor = QtWidgets.QLabel(self.tabInicio)
        self.lbl_autor.setGeometry(QtCore.QRect(930, 570, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lbl_autor.setFont(font)
        self.lbl_autor.setObjectName("lbl_autor")
        self.lbl_logoimg = QtWidgets.QLabel(self.tabInicio)
        self.lbl_logoimg.setGeometry(QtCore.QRect(250, 110, 481, 441))
        self.lbl_logoimg.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_logoimg.setText("")
        self.lbl_logoimg.setObjectName("lbl_logoimg")
        self.label_16 = QtWidgets.QLabel(self.tabInicio)
        self.label_16.setGeometry(QtCore.QRect(890, 570, 55, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.tab.addTab(self.tabInicio, "")
        self.tabWeb = QtWidgets.QWidget()
        self.tabWeb.setObjectName("tabWeb")
        self.label_4 = QtWidgets.QLabel(self.tabWeb)
        self.label_4.setGeometry(QtCore.QRect(10, 340, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tabWeb)
        self.groupBox_7.setGeometry(QtCore.QRect(8, 110, 481, 211))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.lbl_telef = QtWidgets.QLabel(self.groupBox_7)
        self.lbl_telef.setGeometry(QtCore.QRect(20, 40, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_telef.setFont(font)
        self.lbl_telef.setObjectName("lbl_telef")
        self.txt_telef = QtWidgets.QTextEdit(self.groupBox_7)
        self.txt_telef.setEnabled(False)
        self.txt_telef.setGeometry(QtCore.QRect(100, 30, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.txt_telef.setFont(font)
        self.txt_telef.setMouseTracking(False)
        self.txt_telef.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_telef.setObjectName("txt_telef")
        self.label_2 = QtWidgets.QLabel(self.groupBox_7)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 141, 16))
        self.label_2.setObjectName("label_2")
        self.txt_email = QtWidgets.QTextEdit(self.groupBox_7)
        self.txt_email.setEnabled(False)
        self.txt_email.setGeometry(QtCore.QRect(100, 80, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_email.setFont(font)
        self.txt_email.setInputMethodHints(QtCore.Qt.ImhEmailCharactersOnly)
        self.txt_email.setObjectName("txt_email")
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 81, 16))
        self.label_3.setObjectName("label_3")
        self.txt_dir = QtWidgets.QTextEdit(self.groupBox_7)
        self.txt_dir.setEnabled(False)
        self.txt_dir.setGeometry(QtCore.QRect(100, 130, 371, 61))
        self.txt_dir.setObjectName("txt_dir")
        self.lbl_nombWeb = QtWidgets.QLabel(self.tabWeb)
        self.lbl_nombWeb.setGeometry(QtCore.QRect(18, 70, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_nombWeb.setFont(font)
        self.lbl_nombWeb.setObjectName("lbl_nombWeb")
        self.btn_elimJuntDir = QtWidgets.QPushButton(self.tabWeb)
        self.btn_elimJuntDir.setEnabled(False)
        self.btn_elimJuntDir.setGeometry(QtCore.QRect(898, 370, 71, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_elimJuntDir.setFont(font)
        self.btn_elimJuntDir.setObjectName("btn_elimJuntDir")
        self.txt_hist = QtWidgets.QPlainTextEdit(self.tabWeb)
        self.txt_hist.setEnabled(False)
        self.txt_hist.setGeometry(QtCore.QRect(310, 370, 301, 171))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_hist.setFont(font)
        self.txt_hist.setObjectName("txt_hist")
        self.lbl_nombreProy = QtWidgets.QLabel(self.tabWeb)
        self.lbl_nombreProy.setGeometry(QtCore.QRect(18, 20, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_nombreProy.setFont(font)
        self.lbl_nombreProy.setObjectName("lbl_nombreProy")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tabWeb)
        self.groupBox_8.setGeometry(QtCore.QRect(508, 110, 471, 181))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.lbl_logo = QtWidgets.QLabel(self.groupBox_8)
        self.lbl_logo.setGeometry(QtCore.QRect(20, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_logo.setFont(font)
        self.lbl_logo.setObjectName("lbl_logo")
        self.btn_selec_logo = QtWidgets.QToolButton(self.groupBox_8)
        self.btn_selec_logo.setEnabled(False)
        self.btn_selec_logo.setGeometry(QtCore.QRect(420, 30, 31, 31))
        self.btn_selec_logo.setObjectName("btn_selec_logo")
        self.txt_logo = QtWidgets.QTextEdit(self.groupBox_8)
        self.txt_logo.setEnabled(False)
        self.txt_logo.setGeometry(QtCore.QRect(100, 30, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_logo.setFont(font)
        self.txt_logo.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_logo.setObjectName("txt_logo")
        self.label_5 = QtWidgets.QLabel(self.groupBox_8)
        self.label_5.setGeometry(QtCore.QRect(20, 80, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.txt_resum = QtWidgets.QPlainTextEdit(self.groupBox_8)
        self.txt_resum.setEnabled(False)
        self.txt_resum.setGeometry(QtCore.QRect(100, 80, 351, 91))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_resum.setFont(font)
        self.txt_resum.setObjectName("txt_resum")
        self.txt_nombProy = QtWidgets.QTextEdit(self.tabWeb)
        self.txt_nombProy.setEnabled(False)
        self.txt_nombProy.setGeometry(QtCore.QRect(188, 20, 631, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_nombProy.setFont(font)
        self.txt_nombProy.setMouseTracking(False)
        self.txt_nombProy.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_nombProy.setObjectName("txt_nombProy")
        self.txt_nomWeb = QtWidgets.QTextEdit(self.tabWeb)
        self.txt_nomWeb.setEnabled(False)
        self.txt_nomWeb.setGeometry(QtCore.QRect(188, 70, 631, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_nomWeb.setFont(font)
        self.txt_nomWeb.setReadOnly(False)
        self.txt_nomWeb.setObjectName("txt_nomWeb")
        self.listWidget_juntaDir = QtWidgets.QListWidget(self.tabWeb)
        self.listWidget_juntaDir.setEnabled(False)
        self.listWidget_juntaDir.setGeometry(QtCore.QRect(648, 400, 321, 141))
        self.listWidget_juntaDir.setObjectName("listWidget_juntaDir")
        self.txt_sobrenos = QtWidgets.QPlainTextEdit(self.tabWeb)
        self.txt_sobrenos.setEnabled(False)
        self.txt_sobrenos.setGeometry(QtCore.QRect(10, 370, 281, 171))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_sobrenos.setFont(font)
        self.txt_sobrenos.setObjectName("txt_sobrenos")
        self.txt_juntaDir = QtWidgets.QTextEdit(self.tabWeb)
        self.txt_juntaDir.setEnabled(False)
        self.txt_juntaDir.setGeometry(QtCore.QRect(630, 300, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txt_juntaDir.setFont(font)
        self.txt_juntaDir.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_juntaDir.setObjectName("txt_juntaDir")
        self.label_6 = QtWidgets.QLabel(self.tabWeb)
        self.label_6.setGeometry(QtCore.QRect(320, 340, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tabWeb)
        self.label_7.setGeometry(QtCore.QRect(510, 300, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tabWeb)
        self.label_8.setGeometry(QtCore.QRect(648, 370, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.btn_agregarJuntDir = QtWidgets.QPushButton(self.tabWeb)
        self.btn_agregarJuntDir.setEnabled(False)
        self.btn_agregarJuntDir.setGeometry(QtCore.QRect(950, 300, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btn_agregarJuntDir.setFont(font)
        self.btn_agregarJuntDir.setObjectName("btn_agregarJuntDir")
        self.btn_editWeb = QtWidgets.QPushButton(self.tabWeb)
        self.btn_editWeb.setEnabled(False)
        self.btn_editWeb.setGeometry(QtCore.QRect(270, 550, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_editWeb.setFont(font)
        self.btn_editWeb.setObjectName("btn_editWeb")
        self.btn_guardWeb = QtWidgets.QPushButton(self.tabWeb)
        self.btn_guardWeb.setEnabled(False)
        self.btn_guardWeb.setGeometry(QtCore.QRect(420, 550, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_guardWeb.setFont(font)
        self.btn_guardWeb.setObjectName("btn_guardWeb")
        self.btn_cancelEdit = QtWidgets.QPushButton(self.tabWeb)
        self.btn_cancelEdit.setEnabled(False)
        self.btn_cancelEdit.setGeometry(QtCore.QRect(560, 550, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_cancelEdit.setFont(font)
        self.btn_cancelEdit.setObjectName("btn_cancelEdit")
        self.tab.addTab(self.tabWeb, "")
        self.tabPlantilla = QtWidgets.QWidget()
        self.tabPlantilla.setObjectName("tabPlantilla")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tabPlantilla)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 491, 841))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.lbl_img_plActual = QtWidgets.QLabel(self.groupBox)
        self.lbl_img_plActual.setGeometry(QtCore.QRect(80, 30, 301, 511))
        self.lbl_img_plActual.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbl_img_plActual.setText("")
        self.lbl_img_plActual.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_img_plActual.setObjectName("lbl_img_plActual")
        self.btn_editEstilo = QtWidgets.QPushButton(self.groupBox)
        self.btn_editEstilo.setEnabled(False)
        self.btn_editEstilo.setGeometry(QtCore.QRect(112, 550, 111, 28))
        self.btn_editEstilo.setObjectName("btn_editEstilo")
        self.btn_prev = QtWidgets.QPushButton(self.groupBox)
        self.btn_prev.setEnabled(False)
        self.btn_prev.setGeometry(QtCore.QRect(250, 550, 121, 28))
        self.btn_prev.setObjectName("btn_prev")
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tabPlantilla)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(510, 0, 491, 841))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.horizontalLayoutWidget_2)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.comboBox_plantillas = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_plantillas.setGeometry(QtCore.QRect(50, 30, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_plantillas.setFont(font)
        self.comboBox_plantillas.setObjectName("comboBox_plantillas")
        self.comboBox_plantillas.addItem("")
        self.comboBox_plantillas.addItem("")
        self.btn_guardarPlant = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_guardarPlant.setEnabled(False)
        self.btn_guardarPlant.setGeometry(QtCore.QRect(360, 30, 93, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_guardarPlant.setFont(font)
        self.btn_guardarPlant.setObjectName("btn_guardarPlant")
        self.btn_mostrarPlant = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_mostrarPlant.setEnabled(False)
        self.btn_mostrarPlant.setGeometry(QtCore.QRect(260, 30, 93, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_mostrarPlant.setFont(font)
        self.btn_mostrarPlant.setObjectName("btn_mostrarPlant")
        self.lbl_img_plSelec = QtWidgets.QLabel(self.groupBox_2)
        self.lbl_img_plSelec.setGeometry(QtCore.QRect(100, 70, 301, 511))
        self.lbl_img_plSelec.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbl_img_plSelec.setText("")
        self.lbl_img_plSelec.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_img_plSelec.setObjectName("lbl_img_plSelec")
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.tab.addTab(self.tabPlantilla, "")
        self.tabModulos = QtWidgets.QWidget()
        self.tabModulos.setObjectName("tabModulos")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabModulos)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 461, 291))
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn_addNoticia = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_addNoticia.setEnabled(False)
        self.btn_addNoticia.setGeometry(QtCore.QRect(380, 190, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_addNoticia.setFont(font)
        self.btn_addNoticia.setObjectName("btn_addNoticia")
        self.txt_tituloNotic = QtWidgets.QTextEdit(self.groupBox_3)
        self.txt_tituloNotic.setEnabled(False)
        self.txt_tituloNotic.setGeometry(QtCore.QRect(10, 30, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_tituloNotic.setFont(font)
        self.txt_tituloNotic.setObjectName("txt_tituloNotic")
        self.txt_descripNoticia = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txt_descripNoticia.setEnabled(False)
        self.txt_descripNoticia.setGeometry(QtCore.QRect(10, 80, 431, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_descripNoticia.setFont(font)
        self.txt_descripNoticia.setObjectName("txt_descripNoticia")
        self.dateEdit_noticia = QtWidgets.QDateEdit(self.groupBox_3)
        self.dateEdit_noticia.setEnabled(False)
        self.dateEdit_noticia.setGeometry(QtCore.QRect(200, 190, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit_noticia.setFont(font)
        self.dateEdit_noticia.setInputMethodHints(QtCore.Qt.ImhDate|QtCore.Qt.ImhPreferNumbers)
        self.dateEdit_noticia.setObjectName("dateEdit_noticia")
        self.btn_elimTodasNotic = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_elimTodasNotic.setEnabled(False)
        self.btn_elimTodasNotic.setGeometry(QtCore.QRect(120, 250, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_elimTodasNotic.setFont(font)
        self.btn_elimTodasNotic.setObjectName("btn_elimTodasNotic")
        self.btn_verNotic = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_verNotic.setEnabled(False)
        self.btn_verNotic.setGeometry(QtCore.QRect(10, 250, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_verNotic.setFont(font)
        self.btn_verNotic.setObjectName("btn_verNotic")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 190, 181, 21))
        self.label_11.setObjectName("label_11")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabModulos)
        self.groupBox_4.setGeometry(QtCore.QRect(480, 10, 511, 291))
        self.groupBox_4.setObjectName("groupBox_4")
        self.btn_addAct = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_addAct.setEnabled(False)
        self.btn_addAct.setGeometry(QtCore.QRect(440, 200, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_addAct.setFont(font)
        self.btn_addAct.setObjectName("btn_addAct")
        self.btn_verAct = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_verAct.setEnabled(False)
        self.btn_verAct.setGeometry(QtCore.QRect(10, 250, 131, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_verAct.setFont(font)
        self.btn_verAct.setObjectName("btn_verAct")
        self.btn_elimTodasAct = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_elimTodasAct.setEnabled(False)
        self.btn_elimTodasAct.setGeometry(QtCore.QRect(150, 250, 251, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_elimTodasAct.setFont(font)
        self.btn_elimTodasAct.setObjectName("btn_elimTodasAct")
        self.txt_nomAct = QtWidgets.QTextEdit(self.groupBox_4)
        self.txt_nomAct.setEnabled(False)
        self.txt_nomAct.setGeometry(QtCore.QRect(20, 30, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_nomAct.setFont(font)
        self.txt_nomAct.setObjectName("txt_nomAct")
        self.txt_descripAct = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.txt_descripAct.setEnabled(False)
        self.txt_descripAct.setGeometry(QtCore.QRect(20, 80, 481, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_descripAct.setFont(font)
        self.txt_descripAct.setObjectName("txt_descripAct")
        self.timeEdit_act = QtWidgets.QTimeEdit(self.groupBox_4)
        self.timeEdit_act.setEnabled(False)
        self.timeEdit_act.setGeometry(QtCore.QRect(270, 200, 118, 31))
        self.timeEdit_act.setInputMethodHints(QtCore.Qt.ImhPreferNumbers|QtCore.Qt.ImhTime)
        self.timeEdit_act.setObjectName("timeEdit_act")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setGeometry(QtCore.QRect(220, 200, 55, 21))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(20, 200, 61, 21))
        self.label_13.setObjectName("label_13")
        self.dateEdit_actividad = QtWidgets.QDateEdit(self.groupBox_4)
        self.dateEdit_actividad.setEnabled(False)
        self.dateEdit_actividad.setGeometry(QtCore.QRect(80, 200, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit_actividad.setFont(font)
        self.dateEdit_actividad.setInputMethodHints(QtCore.Qt.ImhDate|QtCore.Qt.ImhPreferNumbers)
        self.dateEdit_actividad.setObjectName("dateEdit_actividad")
        self.txt_lugarAct = QtWidgets.QTextEdit(self.groupBox_4)
        self.txt_lugarAct.setEnabled(False)
        self.txt_lugarAct.setGeometry(QtCore.QRect(20, 150, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_lugarAct.setFont(font)
        self.txt_lugarAct.setObjectName("txt_lugarAct")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabModulos)
        self.groupBox_5.setGeometry(QtCore.QRect(480, 310, 511, 271))
        self.groupBox_5.setObjectName("groupBox_5")
        self.btn_addImg = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_addImg.setEnabled(False)
        self.btn_addImg.setGeometry(QtCore.QRect(440, 190, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_addImg.setFont(font)
        self.btn_addImg.setObjectName("btn_addImg")
        self.btn_verImg = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_verImg.setEnabled(False)
        self.btn_verImg.setGeometry(QtCore.QRect(10, 230, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_verImg.setFont(font)
        self.btn_verImg.setObjectName("btn_verImg")
        self.btn_elimTodasImg = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_elimTodasImg.setEnabled(False)
        self.btn_elimTodasImg.setGeometry(QtCore.QRect(140, 230, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_elimTodasImg.setFont(font)
        self.btn_elimTodasImg.setObjectName("btn_elimTodasImg")
        self.btn_selec_img = QtWidgets.QToolButton(self.groupBox_5)
        self.btn_selec_img.setEnabled(False)
        self.btn_selec_img.setGeometry(QtCore.QRect(470, 150, 31, 31))
        self.btn_selec_img.setObjectName("btn_selec_img")
        self.txt_url_img = QtWidgets.QTextEdit(self.groupBox_5)
        self.txt_url_img.setEnabled(False)
        self.txt_url_img.setGeometry(QtCore.QRect(20, 150, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txt_url_img.setFont(font)
        self.txt_url_img.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_url_img.setObjectName("txt_url_img")
        self.lbl_logo_2 = QtWidgets.QLabel(self.groupBox_5)
        self.lbl_logo_2.setGeometry(QtCore.QRect(20, 120, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_logo_2.setFont(font)
        self.lbl_logo_2.setObjectName("lbl_logo_2")
        self.txt_tituloImg = QtWidgets.QTextEdit(self.groupBox_5)
        self.txt_tituloImg.setEnabled(False)
        self.txt_tituloImg.setGeometry(QtCore.QRect(20, 70, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_tituloImg.setFont(font)
        self.txt_tituloImg.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_tituloImg.setObjectName("txt_tituloImg")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tabModulos)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 310, 461, 271))
        self.groupBox_6.setObjectName("groupBox_6")
        self.btn_addEnlace = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_addEnlace.setEnabled(False)
        self.btn_addEnlace.setGeometry(QtCore.QRect(380, 200, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_addEnlace.setFont(font)
        self.btn_addEnlace.setObjectName("btn_addEnlace")
        self.btn_verEnlaces = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_verEnlaces.setEnabled(False)
        self.btn_verEnlaces.setGeometry(QtCore.QRect(10, 230, 101, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_verEnlaces.setFont(font)
        self.btn_verEnlaces.setObjectName("btn_verEnlaces")
        self.btn_elimTodosEnl = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_elimTodosEnl.setEnabled(False)
        self.btn_elimTodosEnl.setGeometry(QtCore.QRect(120, 230, 221, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_elimTodosEnl.setFont(font)
        self.btn_elimTodosEnl.setObjectName("btn_elimTodosEnl")
        self.txt_tituloEnl = QtWidgets.QTextEdit(self.groupBox_6)
        self.txt_tituloEnl.setEnabled(False)
        self.txt_tituloEnl.setGeometry(QtCore.QRect(10, 90, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_tituloEnl.setFont(font)
        self.txt_tituloEnl.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txt_tituloEnl.setObjectName("txt_tituloEnl")
        self.txt_urlEnl = QtWidgets.QTextEdit(self.groupBox_6)
        self.txt_urlEnl.setEnabled(False)
        self.txt_urlEnl.setGeometry(QtCore.QRect(10, 150, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_urlEnl.setFont(font)
        self.txt_urlEnl.setInputMethodHints(QtCore.Qt.ImhUrlCharactersOnly)
        self.txt_urlEnl.setObjectName("txt_urlEnl")
        self.radioBtnFB = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioBtnFB.setEnabled(False)
        self.radioBtnFB.setGeometry(QtCore.QRect(30, 30, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioBtnFB.setFont(font)
        self.radioBtnFB.setObjectName("radioBtnFB")
        self.radioBtnTw = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioBtnTw.setEnabled(False)
        self.radioBtnTw.setGeometry(QtCore.QRect(30, 60, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioBtnTw.setFont(font)
        self.radioBtnTw.setObjectName("radioBtnTw")
        self.radioBtnYt = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioBtnYt.setEnabled(False)
        self.radioBtnYt.setGeometry(QtCore.QRect(180, 30, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioBtnYt.setFont(font)
        self.radioBtnYt.setObjectName("radioBtnYt")
        self.radioBtnPnt = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioBtnPnt.setEnabled(False)
        self.radioBtnPnt.setGeometry(QtCore.QRect(180, 60, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioBtnPnt.setFont(font)
        self.radioBtnPnt.setObjectName("radioBtnPnt")
        self.radioBtnOtro = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioBtnOtro.setEnabled(False)
        self.radioBtnOtro.setGeometry(QtCore.QRect(330, 50, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioBtnOtro.setFont(font)
        self.radioBtnOtro.setObjectName("radioBtnOtro")
        self.tab.addTab(self.tabModulos, "")
        self.tabPublicar = QtWidgets.QWidget()
        self.tabPublicar.setObjectName("tabPublicar")
        self.btnPublicar = QtWidgets.QPushButton(self.tabPublicar)
        self.btnPublicar.setEnabled(False)
        self.btnPublicar.setGeometry(QtCore.QRect(790, 400, 93, 28))
        self.btnPublicar.setObjectName("btnPublicar")
        self.lineEdit_host = QtWidgets.QLineEdit(self.tabPublicar)
        self.lineEdit_host.setEnabled(False)
        self.lineEdit_host.setGeometry(QtCore.QRect(400, 120, 481, 31))
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.lineEdit_usr = QtWidgets.QLineEdit(self.tabPublicar)
        self.lineEdit_usr.setEnabled(False)
        self.lineEdit_usr.setGeometry(QtCore.QRect(400, 170, 481, 31))
        self.lineEdit_usr.setObjectName("lineEdit_usr")
        self.label_9 = QtWidgets.QLabel(self.tabPublicar)
        self.label_9.setGeometry(QtCore.QRect(110, 120, 271, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tabPublicar)
        self.label_10.setGeometry(QtCore.QRect(110, 170, 181, 20))
        self.label_10.setObjectName("label_10")
        self.label_14 = QtWidgets.QLabel(self.tabPublicar)
        self.label_14.setGeometry(QtCore.QRect(110, 220, 211, 20))
        self.label_14.setObjectName("label_14")
        self.lineEdit_psw = QtWidgets.QLineEdit(self.tabPublicar)
        self.lineEdit_psw.setEnabled(False)
        self.lineEdit_psw.setGeometry(QtCore.QRect(400, 220, 481, 31))
        self.lineEdit_psw.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.lineEdit_psw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_psw.setObjectName("lineEdit_psw")
        self.label_15 = QtWidgets.QLabel(self.tabPublicar)
        self.label_15.setGeometry(QtCore.QRect(110, 270, 181, 20))
        self.label_15.setObjectName("label_15")
        self.lineEdit_puerto = QtWidgets.QLineEdit(self.tabPublicar)
        self.lineEdit_puerto.setEnabled(False)
        self.lineEdit_puerto.setGeometry(QtCore.QRect(400, 270, 481, 31))
        self.lineEdit_puerto.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit_puerto.setObjectName("lineEdit_puerto")
        self.tab.addTab(self.tabPublicar, "")
        self.horizontalLayout.addWidget(self.tab)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1011, 26))
        self.menubar.setObjectName("menubar")
        self.menuProyectos = QtWidgets.QMenu(self.menubar)
        self.menuProyectos.setObjectName("menuProyectos")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNuevo_proyecto = QtWidgets.QAction(MainWindow)
        self.actionNuevo_proyecto.setCheckable(False)
        self.actionNuevo_proyecto.setObjectName("actionNuevo_proyecto")
        self.actionAbrir_proyecto = QtWidgets.QAction(MainWindow)
        self.actionAbrir_proyecto.setObjectName("actionAbrir_proyecto")
        self.actionManual_de_usuario = QtWidgets.QAction(MainWindow)
        self.actionManual_de_usuario.setObjectName("actionManual_de_usuario")
        self.actionCerrar_proyecto = QtWidgets.QAction(MainWindow)
        self.actionCerrar_proyecto.setEnabled(False)
        self.actionCerrar_proyecto.setObjectName("actionCerrar_proyecto")
        self.actionPrevisualizar_sitio_web = QtWidgets.QAction(MainWindow)
        self.actionPrevisualizar_sitio_web.setEnabled(False)
        self.actionPrevisualizar_sitio_web.setObjectName("actionPrevisualizar_sitio_web")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.menuProyectos.addAction(self.actionNuevo_proyecto)
        self.menuProyectos.addAction(self.actionAbrir_proyecto)
        self.menuProyectos.addAction(self.actionPrevisualizar_sitio_web)
        self.menuProyectos.addSeparator()
        self.menuProyectos.addAction(self.actionCerrar_proyecto)
        self.menuProyectos.addSeparator()
        self.menuProyectos.addAction(self.actionSalir)
        self.menuAyuda.addAction(self.actionManual_de_usuario)
        self.menubar.addAction(self.menuProyectos.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        self.tab.setCurrentIndex(0)
        self.actionSalir.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WebAsoc Designer"))
        self.label.setText(_translate("MainWindow", "Bienvenido a WebAsoc Designer, el asistente que te permitirá diseñar y crear un sitio web para tu asociación.  "))
        self.lbl_version.setText(_translate("MainWindow", "WebAsoc Designer v1.0"))
        self.lbl_autor.setText(_translate("MainWindow", "cgdelgado"))
        self.label_16.setText(_translate("MainWindow", "2018"))
        self.tab.setTabText(self.tab.indexOf(self.tabInicio), _translate("MainWindow", "Inicio"))
        self.label_4.setText(_translate("MainWindow", "Información sobre la asociación:"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Contacto"))
        self.lbl_telef.setText(_translate("MainWindow", "Teléfono: "))
        self.txt_telef.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Unicode MS\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"><br /></p></body></html>"))
        self.txt_telef.setPlaceholderText(_translate("MainWindow", "Ej.: 999888777"))
        self.label_2.setText(_translate("MainWindow", "Email:"))
        self.txt_email.setPlaceholderText(_translate("MainWindow", "Ej.: mi_correo@electronico.es"))
        self.label_3.setText(_translate("MainWindow", "Dirección: "))
        self.txt_dir.setPlaceholderText(_translate("MainWindow", "Calle, número, piso puerta, CP, Ciudad"))
        self.lbl_nombWeb.setText(_translate("MainWindow", "Nombre del sitio web:"))
        self.btn_elimJuntDir.setText(_translate("MainWindow", "Eliminar "))
        self.lbl_nombreProy.setText(_translate("MainWindow", "Nombre del proyecto: "))
        self.groupBox_8.setTitle(_translate("MainWindow", "Opcional"))
        self.lbl_logo.setText(_translate("MainWindow", "Logotipo:"))
        self.btn_selec_logo.setText(_translate("MainWindow", "..."))
        self.txt_logo.setPlaceholderText(_translate("MainWindow", "jpg, png"))
        self.label_5.setText(_translate("MainWindow", "Resumen:"))
        self.txt_resum.setPlaceholderText(_translate("MainWindow", "Breve resumen sobre el sitio web"))
        self.txt_nombProy.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Unicode MS\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"><br /></p></body></html>"))
        self.txt_nombProy.setPlaceholderText(_translate("MainWindow", "Ej.: Asociacion_vecinos, proyecto1, ProyectoAsociacion (máx 30 caracteres)"))
        self.txt_nomWeb.setPlaceholderText(_translate("MainWindow", "Ej.: Asociación de vecinos de Lagunas (máx 40 caracteres)"))
        self.txt_sobrenos.setPlaceholderText(_translate("MainWindow", "¿Quiénes somos? ¿Qué hacemos?"))
        self.txt_juntaDir.setPlaceholderText(_translate("MainWindow", "Introduzca nombre y apellidos"))
        self.label_6.setText(_translate("MainWindow", "Historia de la asociación:"))
        self.label_7.setText(_translate("MainWindow", "Junta directiva:"))
        self.label_8.setText(_translate("MainWindow", "Seleccione nombre para eliminar"))
        self.btn_agregarJuntDir.setText(_translate("MainWindow", "+"))
        self.btn_editWeb.setText(_translate("MainWindow", "Editar"))
        self.btn_guardWeb.setText(_translate("MainWindow", "Guardar"))
        self.btn_cancelEdit.setText(_translate("MainWindow", "Cancelar"))
        self.tab.setTabText(self.tab.indexOf(self.tabWeb), _translate("MainWindow", "Mi Web"))
        self.groupBox.setTitle(_translate("MainWindow", "Plantilla actual"))
        self.btn_editEstilo.setText(_translate("MainWindow", "Editar estilo"))
        self.btn_prev.setText(_translate("MainWindow", "Previsualizar"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Seleccionar plantilla"))
        self.comboBox_plantillas.setItemText(0, _translate("MainWindow", "Plantilla_1"))
        self.comboBox_plantillas.setItemText(1, _translate("MainWindow", "Plantilla_2"))
        self.btn_guardarPlant.setText(_translate("MainWindow", "Guardar"))
        self.btn_mostrarPlant.setText(_translate("MainWindow", "Mostrar"))
        self.tab.setTabText(self.tab.indexOf(self.tabPlantilla), _translate("MainWindow", "Plantilla y estilo"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Noticias"))
        self.btn_addNoticia.setText(_translate("MainWindow", "Añadir "))
        self.txt_tituloNotic.setPlaceholderText(_translate("MainWindow", "Título"))
        self.txt_descripNoticia.setPlaceholderText(_translate("MainWindow", "Contenido de la noticia"))
        self.btn_elimTodasNotic.setText(_translate("MainWindow", "Eliminar todas las noticias"))
        self.btn_verNotic.setText(_translate("MainWindow", "Ver noticias"))
        self.label_11.setText(_translate("MainWindow", "Fecha de publicación: "))
        self.groupBox_4.setTitle(_translate("MainWindow", "Actividades"))
        self.btn_addAct.setText(_translate("MainWindow", "Añadir "))
        self.btn_verAct.setText(_translate("MainWindow", "Ver actividades"))
        self.btn_elimTodasAct.setText(_translate("MainWindow", "Eliminar todas las actividades"))
        self.txt_nomAct.setPlaceholderText(_translate("MainWindow", "Nombre"))
        self.txt_descripAct.setPlaceholderText(_translate("MainWindow", "Descripción"))
        self.label_12.setText(_translate("MainWindow", "Hora: "))
        self.label_13.setText(_translate("MainWindow", "Fecha: "))
        self.txt_lugarAct.setPlaceholderText(_translate("MainWindow", "Lugar"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Galería de imágenes"))
        self.btn_addImg.setText(_translate("MainWindow", "Añadir "))
        self.btn_verImg.setText(_translate("MainWindow", "Ver imágenes "))
        self.btn_elimTodasImg.setText(_translate("MainWindow", "Eliminar todas las imágenes"))
        self.btn_selec_img.setText(_translate("MainWindow", "..."))
        self.txt_url_img.setPlaceholderText(_translate("MainWindow", "jpg, png"))
        self.lbl_logo_2.setText(_translate("MainWindow", "Seleccionar imagen:"))
        self.txt_tituloImg.setPlaceholderText(_translate("MainWindow", "Título de la imagen"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Enlaces"))
        self.btn_addEnlace.setText(_translate("MainWindow", "Añadir "))
        self.btn_verEnlaces.setText(_translate("MainWindow", "Ver enlaces"))
        self.btn_elimTodosEnl.setText(_translate("MainWindow", "Eliminar todos los enlaces"))
        self.txt_tituloEnl.setPlaceholderText(_translate("MainWindow", "Texto"))
        self.txt_urlEnl.setPlaceholderText(_translate("MainWindow", "URL"))
        self.radioBtnFB.setText(_translate("MainWindow", "Facebook"))
        self.radioBtnTw.setText(_translate("MainWindow", "Twitter"))
        self.radioBtnYt.setText(_translate("MainWindow", "YouTube"))
        self.radioBtnPnt.setText(_translate("MainWindow", "Pinterest"))
        self.radioBtnOtro.setText(_translate("MainWindow", "Otros"))
        self.tab.setTabText(self.tab.indexOf(self.tabModulos), _translate("MainWindow", "Módulo de contenidos"))
        self.btnPublicar.setText(_translate("MainWindow", "Publicar"))
        self.label_9.setText(_translate("MainWindow", "Introduzca el nombre del servidor:"))
        self.label_10.setText(_translate("MainWindow", "Introduzca el usuario:"))
        self.label_14.setText(_translate("MainWindow", "Introduzca la contraseña:"))
        self.label_15.setText(_translate("MainWindow", "Introduzca el puerto:"))
        self.tab.setTabText(self.tab.indexOf(self.tabPublicar), _translate("MainWindow", "Publicar"))
        self.menuProyectos.setTitle(_translate("MainWindow", "Proyectos"))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))
        self.actionNuevo_proyecto.setText(_translate("MainWindow", "Nuevo proyecto"))
        self.actionAbrir_proyecto.setText(_translate("MainWindow", "Abrir proyecto"))
        self.actionManual_de_usuario.setText(_translate("MainWindow", "Manual de usuario"))
        self.actionCerrar_proyecto.setText(_translate("MainWindow", "Cerrar proyecto"))
        self.actionPrevisualizar_sitio_web.setText(_translate("MainWindow", "Previsualizar sitio web"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))

