# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Documentos\UNIVERSIDAD\5to 2016-2017\TFG\Interfaz grafica\editarEstilo.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(504, 489)
        Dialog.setMinimumSize(QtCore.QSize(504, 489))
        Dialog.setMaximumSize(QtCore.QSize(504, 489))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("plantillas/WA.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.h_fontComboBox = QtWidgets.QFontComboBox(Dialog)
        self.h_fontComboBox.setEnabled(True)
        self.h_fontComboBox.setGeometry(QtCore.QRect(250, 310, 224, 22))
        font = QtGui.QFont()
        font.setKerning(True)
        self.h_fontComboBox.setFont(font)
        self.h_fontComboBox.setEditable(False)
        self.h_fontComboBox.setObjectName("h_fontComboBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 70, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 130, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 180, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 310, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(30, 360, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.p_fontComboBox_2 = QtWidgets.QFontComboBox(Dialog)
        self.p_fontComboBox_2.setEnabled(True)
        self.p_fontComboBox_2.setGeometry(QtCore.QRect(250, 360, 224, 22))
        self.p_fontComboBox_2.setEditable(False)
        self.p_fontComboBox_2.setObjectName("p_fontComboBox_2")
        self.lbl_name_web_color = QtWidgets.QLabel(Dialog)
        self.lbl_name_web_color.setGeometry(QtCore.QRect(360, 20, 81, 31))
        self.lbl_name_web_color.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_name_web_color.setText("")
        self.lbl_name_web_color.setObjectName("lbl_name_web_color")
        self.lbl_bg_color_sec = QtWidgets.QLabel(Dialog)
        self.lbl_bg_color_sec.setGeometry(QtCore.QRect(360, 70, 81, 31))
        self.lbl_bg_color_sec.setFrameShape(QtWidgets.QFrame.Panel)
        self.lbl_bg_color_sec.setText("")
        self.lbl_bg_color_sec.setObjectName("lbl_bg_color_sec")
        self.lbl_h_color = QtWidgets.QLabel(Dialog)
        self.lbl_h_color.setGeometry(QtCore.QRect(360, 130, 81, 31))
        self.lbl_h_color.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_h_color.setText("")
        self.lbl_h_color.setObjectName("lbl_h_color")
        self.lbl_p_color_sec = QtWidgets.QLabel(Dialog)
        self.lbl_p_color_sec.setGeometry(QtCore.QRect(360, 180, 81, 31))
        self.lbl_p_color_sec.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_p_color_sec.setText("")
        self.lbl_p_color_sec.setObjectName("lbl_p_color_sec")
        self.btn_valorespredet = QtWidgets.QPushButton(Dialog)
        self.btn_valorespredet.setEnabled(True)
        self.btn_valorespredet.setGeometry(QtCore.QRect(10, 440, 231, 28))
        self.btn_valorespredet.setObjectName("btn_valorespredet")
        self.btn_guardEstilo = QtWidgets.QPushButton(Dialog)
        self.btn_guardEstilo.setGeometry(QtCore.QRect(270, 440, 93, 28))
        self.btn_guardEstilo.setObjectName("btn_guardEstilo")
        self.btn_cancelEdit = QtWidgets.QPushButton(Dialog)
        self.btn_cancelEdit.setGeometry(QtCore.QRect(380, 440, 93, 28))
        self.btn_cancelEdit.setObjectName("btn_cancelEdit")
        self.btn_colorWeb = QtWidgets.QPushButton(Dialog)
        self.btn_colorWeb.setGeometry(QtCore.QRect(440, 20, 31, 31))
        self.btn_colorWeb.setObjectName("btn_colorWeb")
        self.btn_colorbgSecc = QtWidgets.QPushButton(Dialog)
        self.btn_colorbgSecc.setGeometry(QtCore.QRect(440, 70, 31, 31))
        self.btn_colorbgSecc.setObjectName("btn_colorbgSecc")
        self.btn_colorh = QtWidgets.QPushButton(Dialog)
        self.btn_colorh.setGeometry(QtCore.QRect(440, 130, 31, 31))
        self.btn_colorh.setObjectName("btn_colorh")
        self.btn_colorPsec = QtWidgets.QPushButton(Dialog)
        self.btn_colorPsec.setGeometry(QtCore.QRect(440, 180, 31, 31))
        self.btn_colorPsec.setObjectName("btn_colorPsec")
        self.btn_colorP = QtWidgets.QPushButton(Dialog)
        self.btn_colorP.setGeometry(QtCore.QRect(440, 230, 31, 31))
        self.btn_colorP.setObjectName("btn_colorP")
        self.lbl_p_color = QtWidgets.QLabel(Dialog)
        self.lbl_p_color.setGeometry(QtCore.QRect(360, 230, 81, 31))
        self.lbl_p_color.setFrameShape(QtWidgets.QFrame.Box)
        self.lbl_p_color.setText("")
        self.lbl_p_color.setObjectName("lbl_p_color")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(30, 230, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.retranslateUi(Dialog)
        self.btn_cancelEdit.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Editar estilo"))
        self.label.setText(_translate("Dialog", "Color de fondo de la sección:"))
        self.label_2.setText(_translate("Dialog", "Color del nombre del sitio web: "))
        self.label_4.setText(_translate("Dialog", "Color de los títulos: "))
        self.label_5.setText(_translate("Dialog", "Color del texto de párrafos en secciones:"))
        self.label_6.setText(_translate("Dialog", "Fuente de los títulos:"))
        self.label_7.setText(_translate("Dialog", "Fuente del texto: "))
        self.btn_valorespredet.setText(_translate("Dialog", "Restablecer valores predeterminados"))
        self.btn_guardEstilo.setText(_translate("Dialog", "Guardar"))
        self.btn_cancelEdit.setText(_translate("Dialog", "Cancelar"))
        self.btn_colorWeb.setText(_translate("Dialog", "..."))
        self.btn_colorbgSecc.setText(_translate("Dialog", "..."))
        self.btn_colorh.setText(_translate("Dialog", "..."))
        self.btn_colorPsec.setText(_translate("Dialog", "..."))
        self.btn_colorP.setText(_translate("Dialog", "..."))
        self.label_8.setText(_translate("Dialog", "Color del texto de párrafos general:"))

